export interface CompanyData {
  company_name: string;
  company_description: string;
  solution_description: string;
  email: string;
  phone: string;
  website: string;
  activity_item: string;
  emission_source: string;
  description: string;
  carbon_emission: number;
  solution_no: string;
  improvement_measures: string;
}

export const TEST_DATA: { items: CompanyData[] } = {
  "items":[
    {
      "activity_item": "店鋪營運",
      "emission_source": "電力使用",
      "solution_no": "1",
      "company_name": "Delta Electronics (Thailand) PCL",
      "company_description": "Delta Electronics 是泰國主要的能源管理與節能解決方案供應商，專精於智慧能源與自動化。",
      "improvement_measures": "導入能源管理系統（EMS），優化電力使用效率與監控。",
      "solution_description": "Delta EMS 解決方案可協助控管大型建築及連鎖店電力使用，提升能源效率，實現碳減量目標。EMS可自動分析店鋪負載與用電趨勢，建議最佳化運作。",
      "email": "info@deltaww.com",
      "phone": "+66 2 709 2800",
      "website": "https://deltathailand.com/en/energy-management-systems",
      "carbon_emission": 10200,
      "description": "- **排放項目**：店鋪營運 - 電力使用\n- **碳排量**：10200 tCO₂e\n- **建議**：推薦導入能源管理系統，提升用電效率，如 LED 換裝或智能控電規劃。"
    },
    {
      "activity_item": "店鋪營運",
      "emission_source": "電力使用",
      "solution_no": "2",
      "company_name": "GreenYellow Thailand",
      "company_description": "GreenYellow 泰國提供全方位太陽能、節能管理及綠色貸款服務。",
      "improvement_measures": "提供太陽能屋頂建設及綠電採購，降低電力碳排。",
      "solution_description": "GreenYellow 專業規劃與安裝太陽能屋頂及能源管理，以零投資模式讓商業用戶降低用電碳排與成本。",
      "email": "contact@greenyellow.co.th",
      "phone": "+66 2 026 3098",
      "website": "https://www.greenyellow.co.th/en/",
      "carbon_emission": 10200,
      "description": "- **排放項目**：店鋪營運 - 電力使用\n- **碳排量**：10200 tCO₂e\n- **建議**：採用自發自用太陽能，搭配用電尖峰管理，可雙重減碳。"
    },
    {
      "activity_item": "店鋪營運",
      "emission_source": "電力使用",
      "solution_no": "3",
      "company_name": "Kansai Energy Solutions (Thailand) Co., Ltd.",
      "company_description": "日本關西電力集團在泰國的子公司，專注於企業能效改善及節能方案。",
      "improvement_measures": "承接ESCO（能源績效合約）方案，根據店鋪負載提供專業節能設計與監督。",
      "solution_description": "依商用環境量身訂做節能規劃，安裝高效空調與照明系統，監控分析各分店能源消費模式，確保節能績效。",
      "email": "customer@kest.co.th",
      "phone": "+66 2 653 2287",
      "website": "https://www.kest.co.th/",
      "carbon_emission": 10200,
      "description": "- **排放項目**：店鋪營運 - 電力使用\n- **碳排量**：10200 tCO₂e\n- **建議**：採用ESCO服務全面盤查、優化及持續監控，確保真正落實碳減量。"
    },
    {
      "activity_item": "店鋪營運",
      "emission_source": "天然氣使用",
      "solution_no": "1",
      "company_name": "Bangkok Industrial Gas Co., Ltd. (BIG)",
      "company_description": "BIG 是全球空氣產品公司在泰國的據點，聚焦工業氣體、低碳替代與節能技術。",
      "improvement_measures": "協助用戶導入高效率燃燒系統與用氣最佳化，或輔導轉換為低碳燃料。",
      "solution_description": "BIG 提供燃燒優化顧問與節能設備升級設計，還支援燃氣替換減碳選項，協助客戶轉型。",
      "email": "marketing@bigth.com",
      "phone": "+66 2 338 7700",
      "website": "https://bigth.com/en/",
      "carbon_emission": 7300,
      "description": "- **排放項目**：店鋪營運 - 天然氣使用\n- **碳排量**：7300 tCO₂e\n- **建議**：提升燃氣熱效率，逐步導入氫能等替代燃料。"
    },
    {
      "activity_item": "店鋪營運",
      "emission_source": "天然氣使用",
      "solution_no": "2",
      "company_name": "SGS (Thailand) Limited",
      "company_description": "SGS 提供泰國企業多元環境與節能顧問服務，專精於工業能資源管理。",
      "improvement_measures": "進行燃氣能效稽核與最佳化調校，並協助節能認證。",
      "solution_description": "透過監控天然氣鍋爐與燃燒設備效能，建議升級與流程改善，減少不必要損耗，提升系統效率達減碳目標。",
      "email": "thailand@sgs.com",
      "phone": "+66 2 678 1813",
      "website": "https://www.sgs.com/en-th/our-services/industries-and-environment/oil-and-gas",
      "carbon_emission": 7300,
      "description": "- **排放項目**：店鋪營運 - 天然氣使用\n- **碳排量**：7300 tCO₂e\n- **建議**：推行鍋爐與燃燒系統能效提升、稽核與定期調校。"
    },
    {
      "activity_item": "店鋪營運",
      "emission_source": "天然氣使用",
      "solution_no": "3",
      "company_name": "PTT Public Company Limited",
      "company_description": "泰國石油集團（PTT），國家能源轉型領先者，推動企業減碳及再生能源轉型。",
      "improvement_measures": "協助大用戶設計天然氣與替代燃料混合引用，以及應用再生能源減碳。",
      "solution_description": "PTT 透過整體能源規劃，提供低碳燃氣替代與管理顧問，協助企業節能並逐步推進碳中和。",
      "email": "contact@pttplc.com",
      "phone": "+66 2 537 2000",
      "website": "https://www.pttplc.com/en/Sustainability/Environment/Climatechangemanagement.aspx",
      "carbon_emission": 7300,
      "description": "- **排放項目**：店鋪營運 - 天然氣使用\n- **碳排量**：7300 tCO₂e\n- **建議**：規劃轉用再生能源或氫能，並整合用氣效率管理。"
    },
    {
      "activity_item": "店鋪營運",
      "emission_source": "用水",
      "solution_no": "1",
      "company_name": "Thai Energy Conservation Co., Ltd. (Econowatt)",
      "company_description": "泰國知名節能與水處理顧問，提倡企業水電碳排同步減量。",
      "improvement_measures": "提升水資源利用效率、導入回收水系統。",
      "solution_description": "整體水務診斷與系統升級，優化餐飲業及商業設施用水效率、降低抽水能耗與排放。",
      "email": "info@econowatt.co.th",
      "phone": "+66 2 574 0941",
      "website": "https://econowatt.co.th/en/about-us/",
      "carbon_emission": 950,
      "description": "- **排放項目**：店鋪營運 - 用水\n- **碳排量**：950 tCO₂e\n- **建議**：用水端安裝節水設備、回收系統，並進行能耗盤查。"
    },
    {
      "activity_item": "店鋪營運",
      "emission_source": "用水",
      "solution_no": "2",
      "company_name": "Air Liquide Thailand",
      "company_description": "全球法商領導水處理與工業氣體減碳方案，在泰國有完整布建。",
      "improvement_measures": "用氧氣處理提升水回用效率，同步降低能耗與艱難排放。",
      "solution_description": "利用高純度氧加壓提升廢水處理效能，大幅降低能耗碳排，適用大型餐飲與製造用戶。",
      "email": "info.th@airliquide.com",
      "phone": "+66 2 764 7000",
      "website": "https://th.airliquide.com/gas-applications/water-treatment",
      "carbon_emission": 950,
      "description": "- **排放項目**：店鋪營運 - 用水\n- **碳排量**：950 tCO₂e\n- **建議**：推薦使用氧氣節能水處理、節流耗能。"
    },
    {
      "activity_item": "店鋪營運",
      "emission_source": "用水",
      "solution_no": "3",
      "company_name": "NCH Asia (Thailand)",
      "company_description": "專業水處理與工業維護集團，提供工廠、商業碳減量方案。",
      "improvement_measures": "整合水處理、節能及碳排分析，協助企業優化系統。",
      "solution_description": "診斷現場水耗狀況，提供客製化水回收、節能設備與碳足跡管理解決方案。",
      "email": "enquiry@nchasia.com",
      "phone": "+66 2 790 6000",
      "website": "https://www.nchasia.com/en-id/solution/water-treatment/",
      "carbon_emission": 950,
      "description": "- **排放項目**：店鋪營運 - 用水\n- **碳排量**：950 tCO₂e\n- **建議**：園區/總部可考慮全面性整合用水能耗監控及改善。"
    },
    {
      "activity_item": "廚房設備",
      "emission_source": "瓦斯爐燃燒（液化石油氣）",
      "solution_no": "1",
      "company_name": "BE Petrothai Group",
      "company_description": "泰國本土石化及能源創新服務商，主打淨零技術與燃燒減碳。",
      "improvement_measures": "導入高效率燃燒器與調控設備，提升瓦斯爐效率及減碳。",
      "solution_description": "為餐飲、工業廚房設計升級節能爐具、改善燃燒系統，優化熄滅和餘火，降低LPG消耗與碳排。",
      "email": "project@bepetrothai.com",
      "phone": "+66 2 664 4310",
      "website": "https://www.bepetrothai.com/our-products/net-zero-solution-provider",
      "carbon_emission": 3500,
      "description": "- **排放項目**：廚房設備 - 瓦斯爐燃燒（液化石油氣）\n- **碳排量**：3500 tCO₂e\n- **建議**：改用高效率爐頭及智能感測控管系統。"
    },
    {
      "activity_item": "廚房設備",
      "emission_source": "瓦斯爐燃燒（液化石油氣）",
      "solution_no": "2",
      "company_name": "ScienceDirect (Thailand research: Suwansri, S.)",
      "company_description": "專注於生質能與LPG替代方案的泰國學研合作團隊。",
      "improvement_measures": "推廣生質甲烷燃料替代LPG以減少碳排。",
      "solution_description": "為大型廚房設計甲烷燃燒器與供應鏈，協助逐步降低LPG用量、轉用本地生質燃料。",
      "email": "info@sciencedirect.com",
      "phone": "+66 2 000 0000",
      "website": "https://www.sciencedirect.com/science/article/abs/pii/S0973082614000842",
      "carbon_emission": 3500,
      "description": "- **排放項目**：廚房設備 - 瓦斯爐燃燒（液化石油氣）\n- **碳排量**：3500 tCO₂e\n- **建議**：試辦生質燃料爐具，降低LPG碳強度。"
    },
    {
      "activity_item": "廚房設備",
      "emission_source": "瓦斯爐燃燒（液化石油氣）",
      "solution_no": "3",
      "company_name": "Yokogawa Electric (Thailand)",
      "company_description": "專注於碳管理、能源計量、燃燒改善的產業自動化國際大廠。",
      "improvement_measures": "智能燃燒控制、瓦斯檢測及節能顧問。",
      "solution_description": "智慧化燃燒控制器可調整燃燒空氣比與瓦斯流量，配合完整數據監控回饋，實現LPG使用最佳化降低碳排。",
      "email": "info-th@yokogawa.com",
      "phone": "+66 2 530 1500",
      "website": "https://www.yokogawa.com/th/solutions/solutions/carbon-management-solution/",
      "carbon_emission": 3500,
      "description": "- **排放項目**：廚房設備 - 瓦斯爐燃燒（液化石油氣）\n- **碳排量**：3500 tCO₂e\n- **建議**：安裝自動控制器監控消耗，確保燃燒完全。"
    },
    {
      "activity_item": "空調設備",
      "emission_source": "冷媒 R-410A 洩漏",
      "solution_no": "1",
      "company_name": "Daikin Chemical Southeast Asia (Thailand)",
      "company_description": "全球知名冷媒技術供應商，主導低GWP冷媒與漏洩防治。",
      "improvement_measures": "引進低GWP冷媒與智能檢漏系統。",
      "solution_description": "建議定期巡檢維護冷媒管線，採用Daikin低洩漏設計及替換低GWP冷媒，以減少R-410A逃逸。",
      "email": "sales@daikinchemicals.co.th",
      "phone": "+66 2 136 9300",
      "website": "https://daikinchemicals.co.th/en/products/refrigerants",
      "carbon_emission": 0,
      "description": "- **排放項目**：空調設備 - 冷媒 R-410A 洩漏\n- **建議**：定期檢漏並更新為低GWP冷媒，減輕GWP高達2088的碳足跡。"
    },
    {
      "activity_item": "空調設備",
      "emission_source": "冷媒 R-410A 洩漏",
      "solution_no": "2",
      "company_name": "Agramkow (via Ecots Group Thailand)",
      "company_description": "專業氣體檢漏、追蹤及維修設備供應商，聚焦東協市場。",
      "improvement_measures": "安裝工業級自動冷媒檢漏與流量管理系統。",
      "solution_description": "可快速檢測冷媒洩漏點，導入智慧監控平台記錄每一次洩漏並即時排除，並定期檢測全廠冷凍系統。",
      "email": "contact@ecots-group.com",
      "phone": "+66 2 817 9215",
      "website": "https://ecots-group.com/products/technical_products/agramkow.php",
      "carbon_emission": 0,
      "description": "- **排放項目**：空調設備 - 冷媒 R-410A 洩漏\n- **建議**：裝設自動檢漏报警器、導入數據監控平台。"
    },
    {
      "activity_item": "空調設備",
      "emission_source": "冷媒 R-410A 洩漏",
      "solution_no": "3",
      "company_name": "Process Cooling Solutions (Thailand)",
      "company_description": "美國高效率冷卻設備品牌，泰國專業維運代理商。",
      "improvement_measures": "升級成US標準防漏設計冷卻系統，降低壓縮機運作洩漏風險。",
      "solution_description": "工業冷卻系統專業設計，利用高效交換器組件封閉氣體，有效防範R-410A等高溫冷媒逸散。",
      "email": "info@processcoolingsolutions.com",
      "phone": "+66 2 136 7850",
      "website": "https://processcoolingsolutions.com/",
      "carbon_emission": 0,
      "description": "- **排放項目**：空調設備 - 冷媒 R-410A 洩漏\n- **建議**：冷卻主機指定採防漏型機型，同時辦理例行檢修。"
    },
    {
      "activity_item": "物流運輸",
      "emission_source": "食材運輸（柴油車）",
      "solution_no": "1",
      "company_name": "DHL Express (Thailand) Limited",
      "company_description": "全球貨運與物流巨擘，泰國領先永續物流實踐。",
      "improvement_measures": "推動 GoGreen Plus 深度碳追蹤與碳抵消，並引入低碳車隊。",
      "solution_description": "DHL 透過透明碳足跡盤點、提供燃料優化顧問，並推廣燃油高效率駕駛及綠色物流升級。",
      "email": "th.customercare@dhl.com",
      "phone": "+66 2 345 5000",
      "website": "https://www.dhl.com/discover/en-th/logistics-advice/sustainability-and-green-logistics/sustainable-logistics-for-businesses-in-thailand",
      "carbon_emission": 2000,
      "description": "- **排放項目**：物流運輸 - 食材運輸（柴油車）\n- **碳排量**：2000 tCO₂e\n- **建議**：提升車隊維護頻率，引入低排放/高效率車型。"
    },
    {
      "activity_item": "物流運輸",
      "emission_source": "食材運輸（柴油車）",
      "solution_no": "2",
      "company_name": "J&T Express Thailand",
      "company_description": "全國型快遞，持續強化 ESG 與減碳物流發展。",
      "improvement_measures": "推行碳盤查、駕駛訓練改善燃油效率，導入部份電動車替換柴油車。",
      "solution_description": "J&T 以數據追蹤碳排、設置油耗數據平台，積極推進綠色快遞轉型。",
      "email": "contact@jtexpress.co.th",
      "phone": "+66 2 009 5678",
      "website": "https://www.bangkokpost.com/sustainability/3018002/jt-express-advances-green-logistics",
      "carbon_emission": 2000,
      "description": "- **排放項目**：物流運輸 - 食材運輸（柴油車）\n- **碳排量**：2000 tCO₂e\n- **建議**：加強油耗管理，汰換老舊車型。"
    },
    {
      "activity_item": "物流運輸",
      "emission_source": "食材運輸（柴油車）",
      "solution_no": "3",
      "company_name": "Kuehne + Nagel (Thailand) Limited",
      "company_description": "全球前三大物流商，積極推動碳中和運輸。",
      "improvement_measures": "推廣低排放柴油車隊，碳盤查及燃料優化，逐步引入電動或替代能源車。",
      "solution_description": "Kuehne + Nagel 利用智慧路線規劃與升級車隊燃油效率，協助客戶減少食材運輸時的碳排。",
      "email": "info.thailand@kuehne-nagel.com",
      "phone": "+66 2 345 6789",
      "website": "https://newsroom.kuehne-nagel.com/kuehnenagel-paves-the-way-for-sustainable-delivery-solutions-in-thailand-with-lotuss/",
      "carbon_emission": 2000,
      "description": "- **排放項目**：物流運輸 - 食材運輸（柴油車）\n- **碳排量**：2000 tCO₂e\n- **建議**：優化車隊調配與路線，並以泰國新型替代燃料車輛取代舊柴油車。"
    },
    {
      "activity_item": "物流運輸",
      "emission_source": "食材運輸（電動車）",
      "solution_no": "1",
      "company_name": "Electric Vehicles (Thailand) Public Co., Ltd.",
      "company_description": "泰國EV車輛與物流服務公司，專注商用電動車配送整合。",
      "improvement_measures": "提供完整電車物流車隊、充電與能源管理。",
      "solution_description": "量身打造電動物流配送解決方案，提升配送時效並減少碳排總量。",
      "email": "info@evthai.com",
      "phone": "+66 2 236 2020",
      "website": "http://www.evthai.com/",
      "carbon_emission": 1000,
      "description": "- **排放項目**：物流運輸 - 食材運輸（電動車）\n- **碳排量**：1000 tCO₂e\n- **建議**：導入全電車配送、優化充電設施。"
    },
    {
      "activity_item": "物流運輸",
      "emission_source": "食材運輸（電動車）",
      "solution_no": "2",
      "company_name": "DHL Supply Chain Thailand",
      "company_description": "綠色物流轉型龍頭，提供混合電動及 EV 配送方案。",
      "improvement_measures": "提供全區EV車隊，並設置碳盤查資料平台供用戶查詢。",
      "solution_description": "DHL GoGreen及Boots-聯名綠色配送，協助企業達成碳足跡透明化及極低配送碳排量。",
      "email": "th.customercare@dhl.com",
      "phone": "+66 2 345 5000",
      "website": "https://evmagazine.com/articles/dhl-michelin-partner-to-boost-green-logistics-in-thailand",
      "carbon_emission": 1000,
      "description": "- **排放項目**：物流運輸 - 食材運輸（電動車）\n- **碳排量**：1000 tCO₂e\n- **建議**：確保用戶能選擇100%電動車供應綠色配送。"
    },
    {
      "activity_item": "物流運輸",
      "emission_source": "食材運輸（電動車）",
      "solution_no": "3",
      "company_name": "Yusen Logistics Thailand",
      "company_description": "日本綜合物流巨擘，泰國分公司已導入全 EV 貨車隊。",
      "improvement_measures": "物流區 EV 車隊，建立碳排追蹤與管理指標。",
      "solution_description": "Yusen 提供 EV 物流及智能調度系統，在配送的過程中大幅減少碳排生成。",
      "email": "info@yusen-logistics.com",
      "phone": "+66 2 340 8460",
      "website": "https://logistics-manager.com/yusen-logistics-thailand-expands-sustainable-efforts-with-new-ev-truck-fleet-and-charging-station/",
      "carbon_emission": 1000,
      "description": "- **排放項目**：物流運輸 - 食材運輸（電動車）\n- **碳排量**：1000 tCO₂e\n- **建議**：加強電動車調度與配套設施建置。"
    },
    {
      "activity_item": "供應鏈運輸",
      "emission_source": "進口食材運輸（海運）",
      "solution_no": "1",
      "company_name": "Kuehne + Nagel (Thailand) Limited",
      "company_description": "全球海運減碳領導公司，在泰國協助企業完成碳盤查與海運抵換。",
      "improvement_measures": "提供 100% 碳補償/減碳海運服務選項（eShipAsia/FCL Pledge）。",
      "solution_description": "協助用戶選擇全碳中和海運選項，並支持於碳盤查及碳抵換。透明碳足跡報告。",
      "email": "info.thailand@kuehne-nagel.com",
      "phone": "+66 2 345 6789",
      "website": "https://home.kuehne-nagel.com/en/-/services/sea-freight/carbon-offset",
      "carbon_emission": 3100,
      "description": "- **排放項目**：供應鏈運輸 - 進口食材運輸（海運）\n- **碳排量**：3100 tCO₂e\n- **建議**：主動參加零碳運費方案，支持碳中和貨運。"
    },
    {
      "activity_item": "供應鏈運輸",
      "emission_source": "進口食材運輸（海運）",
      "solution_no": "2",
      "company_name": "Kerry Siam Seaport Limited (KSSP)",
      "company_description": "泰國多功能深水海港運營商，致力於港口運營碳減排。",
      "improvement_measures": "智慧港務管理、貨櫃處理自動化，提升運輸減碳。",
      "solution_description": "透過自動化與優化港口運作流程，提升裝卸效率、降低船港碳排。最適合大型進出口食材運輸商。",
      "email": "info@kerrylogistics.com",
      "phone": "+66 2 793 8000",
      "website": "https://www.dcvelocity.com/articles/61052-kerry-siam-seaport-optimizes-operations-and-reduces-carbon-emissions",
      "carbon_emission": 3100,
      "description": "- **排放項目**：供應鏈運輸 - 進口食材運輸（海運）\n- **碳排量**：3100 tCO₂e\n- **建議**：使用智慧化碼頭操作與高能效設備。"
    },
    {
      "activity_item": "供應鏈運輸",
      "emission_source": "進口食材運輸（海運）",
      "solution_no": "3",
      "company_name": "DHL Global Forwarding Thailand",
      "company_description": "國際運輸龍頭，推動綠色物流與碳減排海運方案。",
      "improvement_measures": "提倡海運碳足跡盤查、碳抵消與低碳航線推薦。",
      "solution_description": "DHL 的GoGreen產品讓進口商可跟蹤並抵消每趟海運所產生的碳排放。支援碳中和目標並輔導填報。",
      "email": "th.customercare@dhl.com",
      "phone": "+66 2 345 5000",
      "website": "https://www.dhl.com/th-en/home/sustainability.html",
      "carbon_emission": 3100,
      "description": "- **排放項目**：供應鏈運輸 - 進口食材運輸（海運）\n- **碳排量**：3100 tCO₂e\n- **建議**：進口貨運選擇具碳補償機制的海運業者。"
    },
    {
      "activity_item": "供應鏈運輸",
      "emission_source": "進口食材運輸（航空貨運）",
      "solution_no": "1",
      "company_name": "Kuehne + Nagel (Thailand) Limited",
      "company_description": "空運領先企業，專注於可持續航空燃料與碳減量解決方案。",
      "improvement_measures": "推廣使用Sustainable Aviation Fuel (SAF)及空運碳補償。",
      "solution_description": "用戶可選購 SAF 方案，大幅降低每趟空運的二氧化碳排放。",
      "email": "info.thailand@kuehne-nagel.com",
      "phone": "+66 2 345 6789",
      "website": "https://home.kuehne-nagel.com/en/-/services/air-freight/sustainable-aviation-fuel",
      "carbon_emission": 5800,
      "description": "- **排放項目**：供應鏈運輸 - 進口食材運輸（航空貨運）\n- **碳排量**：5800 tCO₂e\n- **建議**：優先採用含有SAF選項的航空貨運服務。"
    },
    {
      "activity_item": "供應鏈運輸",
      "emission_source": "進口食材運輸（航空貨運）",
      "solution_no": "2",
      "company_name": "Yusen Logistics (Thailand) Co., Ltd.",
      "company_description": "日本全球性物流服務商，泰國分公司倡議低碳空運。",
      "improvement_measures": "空運碳盤查、配合數位碳排追蹤及航空燃料升級。",
      "solution_description": "能根據客戶需求安排較低碳航班，並追蹤排放數據。配合SAF及碳抵消機制提供。",
      "email": "ylth.ml.ssmg.sales.mgt@th.yusen-logistics.com",
      "phone": "+66 2 034 8000",
      "website": "https://www.yusen-logistics.com/th_en/services/end-to-end-transportation/air-freight-forwarding",
      "carbon_emission": 5800,
      "description": "- **排放項目**：供應鏈運輸 - 進口食材運輸（航空貨運）\n- **碳排量**：5800 tCO₂e\n- **建議**：透明計算空運碳排並選擇低碳航線、採碳抵消措施。"
    },
    {
      "activity_item": "供應鏈運輸",
      "emission_source": "進口食材運輸（航空貨運）",
      "solution_no": "3",
      "company_name": "GEODIS Thailand",
      "company_description": "歐洲知名物流服務集團，積極推動泰國低碳空運。",
      "improvement_measures": "協助客戶選用可持續航空燃料與低碳物流路線。",
      "solution_description": "GEODIS 提供SAF空運專案，並協助計算及證明減排成效。",
      "email": "info.apac@geodis.com",
      "phone": "+66 2 960 2099",
      "website": "https://geodis.com/th-en/transport-services/air-freight",
      "carbon_emission": 5800,
      "description": "- **排放項目**：供應鏈運輸 - 進口食材運輸（航空貨運）\n- **碳排量**：5800 tCO₂e\n- **建議**：採用可持續航空燃料、關注空運碳排足跡與抵換措施。"
    },
    {
      "activity_item": "員工通勤",
      "emission_source": "私家車（汽油）",
      "solution_no": "1",
      "company_name": "Toyota Motor Thailand Co., Ltd.",
      "company_description": "知名汽車製造商，積極推動泰國新能源汽車與節能駕駛。",
      "improvement_measures": "推廣油電雙動力與新能源車補助，提升公私通勤節能意識。",
      "solution_description": "協助企業與員工換購油電車或 EV，並推動「Eco-Driving」駕駛訓練，搭配換購獎勵。",
      "email": "csr@toyota.co.th",
      "phone": "+66 2 386 2000",
      "website": "https://www.toyota.co.th/",
      "carbon_emission": 600,
      "description": "- **排放項目**：員工通勤 - 私家車（汽油）\n- **碳排量**：600 tCO₂e\n- **建議**：鼓勵員工以油電車或 EV 替代汽油車，另推動共乘制度。"
    },
    {
      "activity_item": "員工通勤",
      "emission_source": "私家車（汽油）",
      "solution_no": "2",
      "company_name": "SME Climate Hub Thailand",
      "company_description": "國際中小企業碳減量輔導組織，協助計算與改善通勤碳排。",
      "improvement_measures": "推廣共乘、班車、車隊優化、鼓勵綠運輸。",
      "solution_description": "提供碳足跡線上計算、搭配共乘與大眾運輸改善建議，適合辦公園區與餐飲集團。",
      "email": "info@smeclimatehub.org",
      "phone": "+66 2 000 0000",
      "website": "https://smeclimatehub.org/guides/reducing-emissions-from-commuting/",
      "carbon_emission": 600,
      "description": "- **排放項目**：員工通勤 - 私家車（汽油）\n- **碳排量**：600 tCO₂e\n- **建議**：推行員工通勤共乘、辦里程獎勵及鼓勵大眾工具。"
    },
    {
      "activity_item": "員工通勤",
      "emission_source": "私家車（汽油）",
      "solution_no": "3",
      "company_name": "Thai Clean Mobility Programme (TCMP/ GIZ Thailand)",
      "company_description": "致力於泰國交通綠色轉型的德國發展合作項目。",
      "improvement_measures": "推動電動車、低排車輛普及與政策配套。",
      "solution_description": "可結合企業員工購車福利、推動零排放目標，協助大宗企業申請政府節能購車項目。",
      "email": "info@thai-german-cooperation.info",
      "phone": "+66 2 661 9273",
      "website": "https://changing-transport.org/the-future-of-thailand-sustainable-clean-mobility/",
      "carbon_emission": 600,
      "description": "- **排放項目**：員工通勤 - 私家車（汽油）\n- **碳排量**：600 tCO₂e\n- **建議**：推廣低碳車輛換購項目、鼓勵通勤選擇共享/低碳運具。"
    },
    {
      "activity_item": "員工通勤",
      "emission_source": "大眾運輸（電車、捷運）",
      "solution_no": "1",
      "company_name": "Bangkok Mass Transit System (BTS Group Holdings)",
      "company_description": "泰國最大捷運及城市軌道運輸事業，致力於持續轉型綠色交通。",
      "improvement_measures": "提供用電碳補償、大眾乘車獎勵措施與企業合作包票制。",
      "solution_description": "導入再生能源電力、電車碳中和專案，並積極降低每客公里CO₂排放。",
      "email": "customer@bts.co.th",
      "phone": "+66 2 617 6000",
      "website": "https://www.btsgroup.co.th/",
      "carbon_emission": 200,
      "description": "- **排放項目**：員工通勤 - 大眾運輸（電車、捷運）\n- **碳排量**：200 tCO₂e\n- **建議**：推動更多搭捷運、電車之普及，提供企業合作票務優惠。"
    },
    {
      "activity_item": "員工通勤",
      "emission_source": "大眾運輸（電車、捷運）",
      "solution_no": "2",
      "company_name": "TDRI (Thailand Development Research Institute)",
      "company_description": "泰國重要產業政策智庫，倡議公共運輸碳減量與綠交通。",
      "improvement_measures": "政策與現場顧問，輔導企業及地方推動電車碳中和與平台解決方案。",
      "solution_description": "協助地方政府或企業導入電動公交、碳認證捷運及與電池回收鏈結。",
      "email": "contact@tdri.or.th",
      "phone": "+66 2 718 5460",
      "website": "https://tdri.or.th/en/2024/01/braving-hurdles-for-green-transport/",
      "carbon_emission": 200,
      "description": "- **排放項目**：員工通勤 - 大眾運輸（電車、捷運）\n- **碳排量**：200 tCO₂e\n- **建議**：電車/捷運補貼，推動更多低碳公共運輸。"
    },
    {
      "activity_item": "員工通勤",
      "emission_source": "大眾運輸（電車、捷運）",
      "solution_no": "3",
      "company_name": "United Nations Development Programme Thailand",
      "company_description": "聯合國在泰國主導都市低碳轉型專案，協助政策與設施升級。",
      "improvement_measures": "輔導電氣化大眾運輸、提供政策資源、推動民眾搭乘率提升。",
      "solution_description": "大規模支持城市捷運電氣化，協助地方企業規劃電動交通與碳足跡追蹤。",
      "email": "registry.th@undp.org",
      "phone": "+66 2 304 9100",
      "website": "https://www.undp.org/thailand",
      "carbon_emission": 200,
      "description": "- **排放項目**：員工通勤 - 大眾運輸（電車、捷運）\n- **碳排量**：200 tCO₂e\n- **建議**：持續升級公車及捷運配套，強化大眾轉乘效率。"
    },
    {
      "activity_item": "廢棄物管理",
      "emission_source": "餐廚廢棄物處理",
      "solution_no": "1",
      "company_name": "Dow Thailand Group",
      "company_description": "美商陶氏化學泰國，帶領 Food Waste Hub 聯盟與創新食廢管理專案。",
      "improvement_measures": "導入廚餘減量平台與機器，推動堆肥、餘材能源化。",
      "solution_description": "聯合29家機構研發廚餘收集、生物發酵回饋農場，推廣餐飲廚餘分流及即時處理。",
      "email": "info@dow.com",
      "phone": "+66 2 365 7000",
      "website": "https://th.dow.com/en-us/news/press-releases/food-waste-hub-website-20240209.html",
      "carbon_emission": 1200,
      "description": "- **排放項目**：廢棄物管理 - 餐廚廢棄物處理\n- **碳排量**：1200 tCO₂e\n- **建議**：就地廚餘分流，推動堆肥和能源化合作。"
    },
    {
      "activity_item": "廢棄物管理",
      "emission_source": "餐廚廢棄物處理",
      "solution_no": "2",
      "company_name": "UncleRee (Bangkok Tech Startups)",
      "company_description": "新創企業致力於社區廚餘資源化與回收，推動廚餘轉換技術。",
      "improvement_measures": "開發分散式廚餘發酵及生物肥設備，收集處理餐廚廢，轉化有機資源循環。",
      "solution_description": "安裝社區級餐廚廢棄物處理與資源再生小型設備（如生化桶）。",
      "email": "uncle@uncleree.com",
      "phone": "+66 2 000 0000",
      "website": "https://www.unep.org/news-and-stories/story/bangkok-tech-startups-take-food-waste",
      "carbon_emission": 1200,
      "description": "- **排放項目**：廢棄物管理 - 餐廚廢棄物處理\n- **碳排量**：1200 tCO₂e\n- **建議**：設置廚餘桶、合作新創推廣堆肥計畫。"
    },
    {
      "activity_item": "廢棄物管理",
      "emission_source": "餐廚廢棄物處理",
      "solution_no": "3",
      "company_name": "Plaplus Co., Ltd.",
      "company_description": "專攻生質塑料與廢棄物處理服務，為 B2B/B2C 提供廚餘與一般廢棄物再利用。",
      "improvement_measures": "全流程廚餘分流處理並轉換為肥料或能源，減少運輸與掩埋碳排。",
      "solution_description": "設置大型企業餐廚廢棄物收集系統，集中處理能源化、肥料化並追蹤碳減量效益。",
      "email": "support@plaplus.co",
      "phone": "+66 2 000 0000",
      "website": "https://www.secondmuse.com/innovative-entrepreneurship-driving-change-in-thailands-waste-management-landscape/",
      "carbon_emission": 1200,
      "description": "- **排放項目**：廢棄物管理 - 餐廚廢棄物處理\n- **碳排量**：1200 tCO₂e\n- **建議**：大型餐飲廚餘分流、集中轉化資源再利用。"
    },
    {
      "activity_item": "廢水處理",
      "emission_source": "污水處理",
      "solution_no": "1",
      "company_name": "Air Liquide Thailand",
      "company_description": "全球高純度氣體與水處理技術領導品牌，協助泰國廢水碳減排。",
      "improvement_measures": "以高純度氧強化活性污泥法，降低能耗與碳排。",
      "solution_description": "導入氧氣曝氣系統，可顯著提升處理效能，減少CO₂、CH₄、N₂O等溫室氣體逸散。",
      "email": "info.th@airliquide.com",
      "phone": "+66 2 764 7000",
      "website": "https://th.airliquide.com/gas-applications/water-treatment",
      "carbon_emission": 1500,
      "description": "- **排放項目**：廢水處理 - 污水處理\n- **碳排量**：1500 tCO₂e\n- **建議**：使用高效氧曝氣系統，降低整體處理能耗。"
    },
    {
      "activity_item": "廢水處理",
      "emission_source": "污水處理",
      "solution_no": "2",
      "company_name": "NCH Asia (Thailand)",
      "company_description": "工業水處理及廢水管理專家，協助全方位解決三大溫室氣體問題。",
      "improvement_measures": "自動監控與調節廢水處理流程，最高可減少CH₄、N₂O 逸散。",
      "solution_description": "診斷廢水站現行運作流程，優化能源與反應劑用量，降低廢水流放碳排。",
      "email": "enquiry@nchasia.com",
      "phone": "+66 2 790 6000",
      "website": "https://www.nchasia.com/en-id/solution/water-treatment/",
      "carbon_emission": 1500,
      "description": "- **排放項目**：廢水處理 - 污水處理\n- **碳排量**：1500 tCO₂e\n- **建議**：進行能耗碳排盤查，汰換老舊曝氣及回流泵。"
    },
    {
      "activity_item": "廢水處理",
      "emission_source": "污水處理",
      "solution_no": "3",
      "company_name": "Thai Energy Conservation Co., Ltd. (Econowatt)",
      "company_description": "國內節能與廢水零排放專案引領品牌。",
      "improvement_measures": "推動廢水再生循環/回用及污泥密閉處理。",
      "solution_description": "設計再生水流程與封閉式污泥系統，大幅降低CO₂、CH₄排放，確保碳足跡符合 ESG 標準。",
      "email": "info@econowatt.co.th",
      "phone": "+66 2 574 0941",
      "website": "https://econowatt.co.th/en/about-us/",
      "carbon_emission": 1500,
      "description": "- **排放項目**：廢水處理 - 污水處理\n- **碳排量**：1500 tCO₂e\n- **建議**：升級廢水回收系統，並重點減少污泥氣體逸散。"
    }
  ]
};
